# Generated by Django 3.1.1 on 2020-10-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('firstName', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('lastName', models.CharField(default='', max_length=50, verbose_name='Apellidos')),
                ('address', models.CharField(default='', max_length=50, verbose_name='Ciudad')),
                ('address2', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Barrio')),
                ('numIden', models.CharField(default='', max_length=50, unique=True, verbose_name='N° de Identificacion')),
                ('country', models.CharField(choices=[('0', 'Escoger...'), ('COLOMBIA', 'Colombia')], default='0', max_length=50, verbose_name='Pais')),
                ('depart', models.CharField(choices=[('0', 'Escoger...'), ('AMAZONAS', 'Amazonas'), ('ANTIOQUIA', 'Antioquia'), ('ARAUCA', 'Arauca'), ('ATLANTICO', 'Atlantico'), ('BOLIVAR', 'Bolivar'), ('BOYACA', 'Boyaca'), ('CALDAS', 'Caldas'), ('CAQUETA', 'Caqueta'), ('CASANARE', 'Casanare'), ('CAUCA', 'Cauca'), ('CESAR', 'Cesar'), ('CHOCO', 'Choco'), ('CORDOBA', 'Cordoba'), ('CUNDINAMARCA', 'Cundinamarca'), ('GUAINIA', 'Guainia'), ('GUAVIARE', 'Guaviare'), ('HUILA', 'Huila'), ('GUAJIRA', 'La Guajira'), ('MAGDALENA', 'Magdalena'), ('META', 'Meta'), ('NARIÑO', 'Nariño'), ('N/SANTANDER', 'N/Santader'), ('PUTUMAYO', 'Putumayo'), ('QUINDIO', 'Quindio'), ('RISARALDA', 'Risaralda'), ('S/ANDRES', 'S/Andres y Providencia'), ('SANTANDER', 'Santader'), ('SUCRE', 'Sucre'), ('TOLIMA', 'Tolima'), ('VALLE', 'Valle'), ('VAUPES', 'Vaupes'), ('VICHADA', 'Vichada')], default='0', max_length=50, verbose_name='Departamento')),
                ('gender', models.CharField(choices=[('0', 'No Especifica'), ('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('OTROS', 'Otros')], default='0', max_length=50, verbose_name='Tipo de Genero')),
                ('profileImg', models.ImageField(blank=True, null=True, upload_to='profile/img/', verbose_name='Imagen de Perfil')),
                ('postal', models.IntegerField(default=0)),
                ('activeUser', models.BooleanField(default=True)),
                ('admUser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
