# Generated by Django 3.1.1 on 2020-10-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuarios_regisdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='activeUser',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='admUser',
            field=models.BooleanField(default=False, verbose_name='Estado del superusuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='postal',
            field=models.IntegerField(default=0, verbose_name='Codigo Postal'),
        ),
    ]
