# Generated by Django 3.1.1 on 2020-10-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble', models.CharField(max_length=100, verbose_name='Nombre del inmueble')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio de inmueble')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Area construida')),
                ('dirreccion', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('habitaciones', models.IntegerField(default=1)),
                ('baños', models.IntegerField(default=1)),
                ('garaje', models.IntegerField(default=1)),
                ('fotos', models.ImageField(upload_to='property/img', verbose_name='Fotos de descripcion')),
                ('tipoInmueble', models.CharField(choices=[('Alquiler', 'Alquiler'), ('Venta', 'Venta'), ('Campestre', 'Campestre'), ('Terrenos', 'Terrenos')], max_length=50, verbose_name='Tipo de Inmueble')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais/Region')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
            },
        ),
    ]
