# Generated by Django 3.1.1 on 2020-11-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201103_2116'),
        ('stock', '0002_auto_20201103_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usuarios'),
        ),
    ]
