# Generated by Django 3.1.1 on 2020-11-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20201104_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='direccion',
            new_name='addressProperty',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='usuarios',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='baños',
            new_name='bath',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='pais',
            new_name='countryProperty',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='departamento',
            new_name='departProperty',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='descripcion',
            new_name='descrip',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='garaje',
            new_name='garage',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='fotos',
            new_name='imagesRoom',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='precio',
            new_name='priceProperty',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='inmueble',
            new_name='propertyName',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='habitaciones',
            new_name='rooms',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='tipoInmueble',
            new_name='typeProperty',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cityProperty',
            field=models.CharField(default=None, max_length=100, verbose_name='Ciudad'),
        ),
    ]
