# Generated by Django 3.1.1 on 2020-11-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20201104_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='typeProperty',
            field=models.CharField(choices=[('0', 'Escoger...'), ('Alquiler', 'Alquiler'), ('Venta', 'Venta'), ('Campestre', 'Campestre'), ('Terrenos', 'Terrenos')], max_length=50, verbose_name='Tipo de Inmueble'),
        ),
    ]
