# Generated by Django 3.1.1 on 2020-11-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20201104_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='typeService',
            field=models.CharField(choices=[('Alquiler', 'Alquiler'), ('Venta', 'Venta')], default=None, max_length=50, verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='countryProperty',
            field=models.CharField(choices=[('0', 'Escoger...'), ('COLOMBIA', 'Colombia')], default=None, max_length=50, verbose_name='Pais/Region'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='departProperty',
            field=models.CharField(choices=[('0', 'Escoger...'), ('AMAZONAS', 'Amazonas'), ('ANTIOQUIA', 'Antioquia'), ('ARAUCA', 'Arauca'), ('ATLANTICO', 'Atlantico'), ('BOLIVAR', 'Bolivar'), ('BOYACA', 'Boyaca'), ('CALDAS', 'Caldas'), ('CAQUETA', 'Caqueta'), ('CASANARE', 'Casanare'), ('CAUCA', 'Cauca'), ('CESAR', 'Cesar'), ('CHOCO', 'Choco'), ('CORDOBA', 'Cordoba'), ('CUNDINAMARCA', 'Cundinamarca'), ('GUAINIA', 'Guainia'), ('GUAVIARE', 'Guaviare'), ('HUILA', 'Huila'), ('GUAJIRA', 'La Guajira'), ('MAGDALENA', 'Magdalena'), ('META', 'Meta'), ('NARIÑO', 'Nariño'), ('N/SANTANDER', 'N/Santader'), ('PUTUMAYO', 'Putumayo'), ('QUINDIO', 'Quindio'), ('RISARALDA', 'Risaralda'), ('S/ANDRES', 'S/Andres y Providencia'), ('SANTANDER', 'Santader'), ('SUCRE', 'Sucre'), ('TOLIMA', 'Tolima'), ('VALLE', 'Valle'), ('VAUPES', 'Vaupes'), ('VICHADA', 'Vichada')], default=None, max_length=50, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='typeProperty',
            field=models.CharField(choices=[('Apartamentos', 'Apartamentos'), ('Oficinas', 'Oficinas '), ('Campestre', 'Campestre'), ('Terrenos', 'Terrenos')], default=None, max_length=50, verbose_name='Tipo de Inmueble'),
        ),
    ]
