# Generated by Django 3.1.1 on 2020-12-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20201107_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='countryProperty',
            field=models.CharField(choices=[('COLOMBIA', 'Colombia')], default=None, max_length=50, verbose_name='Pais/Region'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='departProperty',
            field=models.CharField(choices=[('AMAZONAS', 'Amazonas'), ('ANTIOQUIA', 'Antioquia'), ('ARAUCA', 'Arauca'), ('ATLANTICO', 'Atlantico'), ('BOLIVAR', 'Bolivar'), ('BOYACA', 'Boyaca'), ('CALDAS', 'Caldas'), ('CAQUETA', 'Caqueta'), ('CASANARE', 'Casanare'), ('CAUCA', 'Cauca'), ('CESAR', 'Cesar'), ('CHOCO', 'Choco'), ('CORDOBA', 'Cordoba'), ('CUNDINAMARCA', 'Cundinamarca'), ('GUAINIA', 'Guainia'), ('GUAVIARE', 'Guaviare'), ('HUILA', 'Huila'), ('GUAJIRA', 'La Guajira'), ('MAGDALENA', 'Magdalena'), ('META', 'Meta'), ('NARIÑO', 'Nariño'), ('N/SANTANDER', 'N/Santader'), ('PUTUMAYO', 'Putumayo'), ('QUINDIO', 'Quindio'), ('RISARALDA', 'Risaralda'), ('S/ANDRES', 'S/Andres y Providencia'), ('SANTANDER', 'Santader'), ('SUCRE', 'Sucre'), ('TOLIMA', 'Tolima'), ('VALLE', 'Valle'), ('VAUPES', 'Vaupes'), ('VICHADA', 'Vichada')], default=None, max_length=50, verbose_name='Departamento'),
        ),
    ]
