# Generated by Django 3.1.1 on 2021-02-17 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=50, verbose_name='Ciudad')),
                ('streets', models.CharField(blank=True, default='', max_length=50, verbose_name='Barrio')),
                ('numIden', models.PositiveBigIntegerField(default=None, unique=True, verbose_name='N° de Identificacion')),
                ('numPhone', models.PositiveBigIntegerField(default='0', verbose_name='N° de Telefono')),
                ('country', models.CharField(choices=[('0', 'Escoger...'), ('COLOMBIA', 'Colombia')], default='', max_length=50, verbose_name='Pais')),
                ('depart', models.CharField(choices=[('0', 'Escoger...'), ('AMAZONAS', 'Amazonas'), ('ANTIOQUIA', 'Antioquia'), ('ARAUCA', 'Arauca'), ('ATLANTICO', 'Atlantico'), ('BOLIVAR', 'Bolivar'), ('BOYACA', 'Boyaca'), ('CALDAS', 'Caldas'), ('CAQUETA', 'Caqueta'), ('CASANARE', 'Casanare'), ('CAUCA', 'Cauca'), ('CESAR', 'Cesar'), ('CHOCO', 'Choco'), ('CORDOBA', 'Cordoba'), ('CUNDINAMARCA', 'Cundinamarca'), ('GUAINIA', 'Guainia'), ('GUAVIARE', 'Guaviare'), ('HUILA', 'Huila'), ('GUAJIRA', 'La Guajira'), ('MAGDALENA', 'Magdalena'), ('META', 'Meta'), ('NARIÑO', 'Nariño'), ('N/SANTANDER', 'N/Santader'), ('PUTUMAYO', 'Putumayo'), ('QUINDIO', 'Quindio'), ('RISARALDA', 'Risaralda'), ('S/ANDRES', 'S/Andres y Providencia'), ('SANTANDER', 'Santader'), ('SUCRE', 'Sucre'), ('TOLIMA', 'Tolima'), ('VALLE', 'Valle'), ('VAUPES', 'Vaupes'), ('VICHADA', 'Vichada')], default='0', max_length=50, verbose_name='Departamento')),
                ('gender', models.CharField(choices=[('0', 'No Especifica'), ('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('OTROS', 'Otros')], default='0', max_length=50, verbose_name='Tipo de Genero')),
                ('profileImg', models.ImageField(blank=True, null=True, upload_to='source/profile/img/', verbose_name='Imagen de Perfil')),
                ('regisDate', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('postal', models.IntegerField(default=0, verbose_name='Codigo Postal')),
                ('birthday', models.DateField(default=None, verbose_name='Fecha de Nacimiento')),
                ('usuario', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tabla de perfil',
                'verbose_name_plural': 'Tabla de perfiles',
            },
        ),
    ]
