# Generated by Django 3.1.1 on 2020-10-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='regisDate',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
    ]
