# Generated by Django 3.1.1 on 2020-10-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201001_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='activeUser',
            field=models.BooleanField(default=True, help_text='Designa si este usuario debe tratarse como activo. Deseleccione esto en lugar de eliminar cuentas.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='admUser',
            field=models.BooleanField(default=False, help_text='Designa que este usuario tiene todos los permisos sin asignarlos explícitamente.', verbose_name='Estado del superusuario'),
        ),
    ]
