# Generated by Django 3.1.1 on 2020-12-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201103_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='numPhone',
            field=models.IntegerField(default='0', verbose_name='N° de Telefono'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='country',
            field=models.CharField(choices=[('0', 'Escoger...'), ('COLOMBIA', 'Colombia')], default='', max_length=50, verbose_name='Pais'),
        ),
    ]
